/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import programa.DiretorDaEscola;
import programa.EntidadeDoGoverno;
import programa.Escola;
import programa.GerenciadorDeArquivos;

/**
 *
 * @author Marcos Eduardo
 */
public class TelaCadastroDiretor extends javax.swing.JFrame {
    private JFrame paginaAnterior;
    private ArrayList<String> nomeEscolas = new ArrayList<>();
    private ArrayList<Escola> escolas = new ArrayList<>();
    private ArrayList<DiretorDaEscola> diretores = new ArrayList<>();
    private ArrayList<EntidadeDoGoverno> entidades = new ArrayList<>();
    /**
     * Creates new form NewJFrame
     */
    public TelaCadastroDiretor(JFrame paginaAnterior) {
        this.paginaAnterior = paginaAnterior;
        File f = new File("src\\dados\\escolas.txt");
        GerenciadorDeArquivos<Escola> gerenciadorDeArquivos = new GerenciadorDeArquivos<>();
        try {
            escolas = gerenciadorDeArquivos.lerArquivo(f);
            for (Escola escola : escolas) {
                if (escola.getDiretor() == null) {
                    nomeEscolas.add(escola.getNome());
                }
            }
            initComponents();
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null,"Não foi possível carregar as escolas disponíveis","ERRO" ,JOptionPane.ERROR_MESSAGE);
            paginaAnterior.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        campoNome = new javax.swing.JTextField();
        campoLogin = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botaoCadastro = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        seletorEscola = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JFormattedTextField();
        campoCpf = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Diretor");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/brasil.png")).getImage());

        jLabel3.setText("Nome:");

        jLabel4.setText("Login:");

        jLabel5.setText("Senha:");

        jLabel6.setText("CPF:");

        jLabel7.setText(" Tel:");

        botaoCadastro.setText("Cadastrar");
        botaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroActionPerformed(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        seletorEscola.setModel(new javax.swing.DefaultComboBoxModel(nomeEscolas.toArray()));
        seletorEscola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletorEscolaActionPerformed(evt);
            }
        });

        jLabel1.setText("Escola:");

        try {
            campoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefoneActionPerformed(evt);
            }
        });

        try {
            campoCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(seletorEscola, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(botaoCadastro)
                        .addGap(18, 18, 18)
                        .addComponent(botaoVoltar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(campoTelefone)
                            .addComponent(campoCpf))))
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(seletorEscola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCadastro)
                    .addComponent(botaoVoltar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroActionPerformed
        if(campoCpf.getText().isBlank() || 
                campoTelefone.getText().isBlank() ||
                campoLogin.getText().isBlank() || 
                campoNome.getText().isBlank() ||
                new String(campoSenha.getPassword()).isBlank()
                ){ 
            JOptionPane.showMessageDialog(null,"Por favor preencha todos os campos para o cadastro","AVISO" ,JOptionPane.WARNING_MESSAGE);
        }
        else{
            try {
                boolean loginJaExiste = false;
                int indice = 0;
                File arquivoDiretores = new File("src\\dados\\usuarios\\diretores.txt");
                File arquivoEscolas = new File("src\\dados\\escolas.txt");
                File arquivoEntidades = new File("src\\dados\\usuarios\\entidades.txt");
                GerenciadorDeArquivos<DiretorDaEscola> gerenciadorDeArquivosDiretor = new GerenciadorDeArquivos<>();
                GerenciadorDeArquivos<Escola> gerenciadorDeArquivosEscola = new  GerenciadorDeArquivos<>();
                GerenciadorDeArquivos<EntidadeDoGoverno> gerenciadorDeArquivosEntidades = new GerenciadorDeArquivos<>();
                if (!arquivoDiretores.isDirectory() && arquivoDiretores.exists()) {
                    diretores = gerenciadorDeArquivosDiretor.lerArquivo(arquivoDiretores);
                }
                if (!arquivoEntidades.isDirectory() && arquivoEntidades.exists()) {
                    entidades = gerenciadorDeArquivosEntidades.lerArquivo(arquivoEntidades);
                }
                for (int i = 0; i < escolas.size(); i++) {
                    if(seletorEscola.getSelectedItem().equals(escolas.get(i).getNome())){
                        indice = i;
                        break;
                    }
                }
                DiretorDaEscola novoDiretor = new DiretorDaEscola(Long.parseLong(campoCpf.getText()),
                        campoTelefone.getText(),
                        campoLogin.getText(),
                        new String(campoSenha.getPassword()),
                        campoNome.getText(),
                        escolas.get(indice));
                
                for (DiretorDaEscola diretor : diretores) {
                    if(diretor.getLogin().equals(novoDiretor.getLogin())|| 
                        diretor.getCpf() == novoDiretor.getCpf()){
                        loginJaExiste = true;
                    }
                }
                for (EntidadeDoGoverno entidade : entidades) {
                    if(entidade.getLogin().equals(novoDiretor.getLogin())){
                        loginJaExiste = true;
                    }
                }
                if (!loginJaExiste) {
                    diretores.add(novoDiretor);
                    escolas.get(indice).setDiretor(novoDiretor);
                    gerenciadorDeArquivosDiretor.EscreverArquivo(diretores, arquivoDiretores);
                    gerenciadorDeArquivosEscola.EscreverArquivo(escolas, arquivoEscolas);
                    ((TelaInicial) paginaAnterior).setDiretoresCadastrados(diretores);
                    botaoVoltarActionPerformed(evt);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Este usuário já existe, por favor verifique seu login ou seu cpf","AVISO" ,JOptionPane.WARNING_MESSAGE);
                }
            }
            catch (HeadlessException | IOException | ClassNotFoundException | NumberFormatException e) {
                JOptionPane.showMessageDialog(null,"Ocorreu um Erro com o Arquivo de Entidades (" + e.toString() + ")" ,"ERRO" ,JOptionPane.ERROR_MESSAGE);
                botaoVoltarActionPerformed(evt);
            } 
        }
    }//GEN-LAST:event_botaoCadastroActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        paginaAnterior.setVisible(true);
        this.setVisible(false);
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void campoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefoneActionPerformed

    private void seletorEscolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorEscolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seletorEscolaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastro;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JFormattedTextField campoCpf;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JFormattedTextField campoTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> seletorEscola;
    // End of variables declaration//GEN-END:variables
}
