package Telas;

import javax.swing.JFrame;

/**
 *
 * @author lucas
 */
public class TelaEntidade extends javax.swing.JFrame {
    private JFrame paginaAnterior;
    /**
     * Creates new form TelaEntidade
     */
    public TelaEntidade(JFrame paginaAnterior) {
        this.paginaAnterior = paginaAnterior;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPedidos = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtChamados = new javax.swing.JTextPane();
        btPedidos = new javax.swing.JButton();
        btEnergia = new javax.swing.JButton();
        btComputadores = new javax.swing.JButton();
        btInternet = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bem Vindo Sr.");

        jScrollPane1.setViewportView(txtPedidos);

        jScrollPane2.setViewportView(txtChamados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/entrega-de-pedido (1).png"))); // NOI18N
        btPedidos.setText("Pedidos");
        btPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidosActionPerformed(evt);
            }
        });

        btEnergia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/energia-solar (1).png"))); // NOI18N
        btEnergia.setText("Energia");
        btEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnergiaActionPerformed(evt);
            }
        });

        btComputadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/computador (1).png"))); // NOI18N
        btComputadores.setText("Computadores");
        btComputadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComputadoresActionPerformed(evt);
            }
        });

        btInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/internet.png"))); // NOI18N
        btInternet.setText("Internet");
        btInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInternetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btPedidos)
                        .addGap(28, 28, 28)
                        .addComponent(btEnergia)
                        .addGap(28, 28, 28)
                        .addComponent(btComputadores)
                        .addGap(18, 18, 18)
                        .addComponent(btInternet)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPedidos)
                    .addComponent(btEnergia)
                    .addComponent(btComputadores)
                    .addComponent(btInternet))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnergiaActionPerformed
        TelaEnergia telaenergia = new TelaEnergia(this);
        telaenergia.setLocationRelativeTo(null);
        telaenergia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btEnergiaActionPerformed

    private void btPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidosActionPerformed
        TelaPedidos telapedidos = new TelaPedidos(this);
        telapedidos.setLocationRelativeTo(null);
        telapedidos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btPedidosActionPerformed

    private void btComputadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComputadoresActionPerformed
        TelaComputador telacomputador = new TelaComputador(this);
        telacomputador.setLocationRelativeTo(null);
        telacomputador.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btComputadoresActionPerformed

    private void btInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInternetActionPerformed
        TelaInternet telainternet = new TelaInternet(this);
        telainternet.setLocationRelativeTo(null);
        telainternet.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btInternetActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btComputadores;
    private javax.swing.JButton btEnergia;
    private javax.swing.JButton btInternet;
    private javax.swing.JButton btPedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane txtChamados;
    private javax.swing.JTextPane txtPedidos;
    // End of variables declaration//GEN-END:variables
}
