/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import programa.DiretorDaEscola;
import programa.EntidadeDoGoverno;
import programa.Escola;
import programa.GerenciadorDeArquivos;
import programa.Usuario;

/**
 *
 * @author Marcos Eduardo
 */
public class TelaInicial extends javax.swing.JFrame {
       private ArrayList<EntidadeDoGoverno> entidadesCadastradas = new ArrayList<>();

    public void setEntidadesCadastradas(ArrayList<EntidadeDoGoverno> entidadesCadastradas) {
        this.entidadesCadastradas = entidadesCadastradas;
    }

    public void setDiretoresCadastrados(ArrayList<DiretorDaEscola> diretoresCadastrados) {
        this.diretoresCadastrados = diretoresCadastrados;
    }
       private ArrayList<DiretorDaEscola> diretoresCadastrados  = new ArrayList<>();
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        File f = new File("src\\dados\\escolas.txt" );
        if(!f.isDirectory() && !f.exists()){ // Inicialização do Arquivo de Escolas caso não exista
            try {
                ArrayList<Escola> escolas = new ArrayList<>();
                Random rand = new Random();
                for (int i = 1; i <= 15; i++) {
                    Escola escola = new Escola(i,
                            rand.nextInt(30, 100),
                            rand.nextInt(0, 100),
                            "Bairo " + i,
                            "DF",
                            "Brasília",
                            i,
                            (float) i,
                            (float) i,
                            false,
                            false,
                            "Escola" + i);
                    escolas.add(escola);
                }
                GerenciadorDeArquivos<Escola> gerenciadorDeArquivos = new GerenciadorDeArquivos<>();
                gerenciadorDeArquivos.EscreverArquivo(escolas, f);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null,"Ocorreu um Erro Durante a Inicialização do Arquivo de Escolas (" + e.toString() + ")" ,"ERRO" ,JOptionPane.ERROR_MESSAGE);
                this.dispose();
            }
            try {
                File arquivoEntidades = new File("src\\dados\\usuarios\\entidades.txt");
                File arquivoDiretores = new File("src\\dados\\usuarios\\diretores.txt");
                GerenciadorDeArquivos<EntidadeDoGoverno> gerenciadorDeArquivosEntidades = new GerenciadorDeArquivos<>();
                GerenciadorDeArquivos<DiretorDaEscola> gerenciadorDeArquivosDiretores = new GerenciadorDeArquivos<>();
                if (!arquivoEntidades.isDirectory() && arquivoEntidades.exists()) {
                    entidadesCadastradas = gerenciadorDeArquivosEntidades.lerArquivo(arquivoEntidades);
                }
                if (!arquivoDiretores.isDirectory() && arquivoDiretores.exists()) {
                   diretoresCadastrados = gerenciadorDeArquivosDiretores.lerArquivo(arquivoDiretores); 
                }
            } catch (IOException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null,"Ocorreu um Erro ao abrir os arquivos Usuários (" + e.toString() + ")" ,"ERRO" ,JOptionPane.ERROR_MESSAGE);
                this.dispose();
            }
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        botaoEntrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botaoCadastrarEntidade = new javax.swing.JButton();
        botaoCadastrarDiretor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Página Inicial");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/brasil.png")).getImage());

        jLabel2.setText("Login:");

        campoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLoginActionPerformed(evt);
            }
        });

        jLabel1.setText("Senha: ");

        botaoEntrar.setText("Entrar");
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoSenha)
                            .addComponent(campoLogin)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(botaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(botaoEntrar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/brasil.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Escolas Conectadas");

        botaoCadastrarEntidade.setText("Cadastrar Nova Entidade");
        botaoCadastrarEntidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarEntidadeActionPerformed(evt);
            }
        });

        botaoCadastrarDiretor.setText("Cadastrar Novo Diretor");
        botaoCadastrarDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarDiretorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jLabel4.setText("Ainda não tem acesso?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoCadastrarDiretor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoCadastrarEntidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(botaoCadastrarDiretor)
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrarEntidade)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarEntidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarEntidadeActionPerformed
            TelaCadastroEntidade telaCadastroEntidade = new TelaCadastroEntidade(this);
            telaCadastroEntidade.setLocationRelativeTo(null);
            telaCadastroEntidade.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_botaoCadastrarEntidadeActionPerformed

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        boolean encontrouUsuario = false;
        JFrame proximaPagina = null;
        if (campoLogin.getText().isBlank() ||  new String(campoSenha.getPassword()).isBlank()) {
            JOptionPane.showMessageDialog(null,"Por favor preencha todos os campos para entrar","AVISO" ,JOptionPane.WARNING_MESSAGE);
        }
        else{
            for (EntidadeDoGoverno entidade: entidadesCadastradas) {
                if (entidade.getLogin().equals(campoLogin.getText())) {
                    encontrouUsuario = true;
                    if (entidade.getSenha().equals(new String(campoSenha.getPassword()))) {
                        proximaPagina = new TelaEntidade(this);
                    }
                }
            }
            if (!encontrouUsuario) {
                for (DiretorDaEscola diretor : diretoresCadastrados) {
                    if (diretor.getLogin().equals(campoLogin.getText())) {
                        encontrouUsuario = true;
                        if (diretor.getSenha().equals(new String(campoSenha.getPassword()))) {
                        }
                    }
                }
            }
            if (encontrouUsuario) {
                if (proximaPagina != null) {
                    proximaPagina.setLocationRelativeTo(null);
                    proximaPagina.setVisible(true);
                    this.setVisible(false);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Senha Incorreta","AVISO" ,JOptionPane.WARNING_MESSAGE);
                }
            }
            else{
               JOptionPane.showMessageDialog(null,"Usuário Não Cadastrado","AVISO" ,JOptionPane.WARNING_MESSAGE); 
            }
        }
    }//GEN-LAST:event_botaoEntrarActionPerformed

    private void campoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLoginActionPerformed

    private void botaoCadastrarDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarDiretorActionPerformed
        TelaCadastroDiretor telaCadastroDiretor = new  TelaCadastroDiretor(this);
        telaCadastroDiretor.setLocationRelativeTo(null);
        telaCadastroDiretor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botaoCadastrarDiretorActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              TelaInicial telaInicial =  new TelaInicial();
              telaInicial.setLocationRelativeTo(null);
              telaInicial.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrarDiretor;
    private javax.swing.JButton botaoCadastrarEntidade;
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
