package Telas;

import javax.swing.JFrame;
import programa.EntidadeDoGoverno;


public class TelaEntidade extends javax.swing.JFrame {
    private JFrame paginaAnterior;
    private EntidadeDoGoverno entidade;
    /**
     * Creates new form TelaEntidade
     */
    public TelaEntidade(JFrame paginaAnterior,EntidadeDoGoverno entidade) {
        this.paginaAnterior = paginaAnterior;
        this.entidade = entidade;
        initComponents();
        setarTexto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btPedidos = new javax.swing.JButton();
        btEnergia = new javax.swing.JButton();
        btComputadores = new javax.swing.JButton();
        btInternet = new javax.swing.JButton();
        labelpedidos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entidade Governamental");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/brasil.png")).getImage());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/brasil.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Escolas Conectadas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        btPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/entrega-de-pedido (1).png"))); // NOI18N
        btPedidos.setText("Pedidos");
        btPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidosActionPerformed(evt);
            }
        });

        btEnergia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/energia-solar (1).png"))); // NOI18N
        btEnergia.setText("Energia");
        btEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnergiaActionPerformed(evt);
            }
        });

        btComputadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/computador (1).png"))); // NOI18N
        btComputadores.setText("Computadores");
        btComputadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComputadoresActionPerformed(evt);
            }
        });

        btInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/internet.png"))); // NOI18N
        btInternet.setText("Internet");
        btInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInternetActionPerformed(evt);
            }
        });

        labelpedidos.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btComputadores, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelpedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelpedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPedidos)
                .addGap(18, 18, 18)
                .addComponent(btEnergia)
                .addGap(18, 18, 18)
                .addComponent(btInternet)
                .addGap(18, 18, 18)
                .addComponent(btComputadores)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setarTexto(){
        String txt1 = "Total de x pedidos a serem realizados";
        labelpedidos.setText(txt1);
        
    }
    private void btEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnergiaActionPerformed
        TelaEnergia telaenergia = new TelaEnergia(this,entidade);
        telaenergia.setLocationRelativeTo(null);
        telaenergia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btEnergiaActionPerformed

    private void btPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidosActionPerformed
        TelaPedidos telapedidos = new TelaPedidos(this,entidade);
        telapedidos.setLocationRelativeTo(null);
        telapedidos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btPedidosActionPerformed

    private void btComputadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComputadoresActionPerformed
        TelaComputador telacomputador = new TelaComputador(this,entidade);
        telacomputador.setLocationRelativeTo(null);
        telacomputador.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btComputadoresActionPerformed

    private void btInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInternetActionPerformed
        TelaInternet telainternet = new TelaInternet(this,entidade);
        telainternet.setLocationRelativeTo(null);
        telainternet.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btInternetActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btComputadores;
    private javax.swing.JButton btEnergia;
    private javax.swing.JButton btInternet;
    private javax.swing.JButton btPedidos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelpedidos;
    // End of variables declaration//GEN-END:variables
}
