package Telas;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import programa.EntidadeDoGoverno;


public class TelaEntidade extends javax.swing.JFrame {
    private JFrame paginaAnterior;
    private EntidadeDoGoverno entidade;
    /**
     * Creates new form TelaEntidade
     */
    public TelaEntidade(JFrame paginaAnterior,EntidadeDoGoverno entidade) {
        this.paginaAnterior = paginaAnterior;
        this.entidade = entidade;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btPedidos = new javax.swing.JButton();
        btEnergia = new javax.swing.JButton();
        btComputadores = new javax.swing.JButton();
        btInternet = new javax.swing.JButton();
        btNome = new javax.swing.JButton();
        btSenha = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entidade Governamental");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/brasil.png")).getImage());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/brasil.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Escolas Conectadas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );

        btPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/entrega-de-pedido (1).png"))); // NOI18N
        btPedidos.setText("Pedidos");
        btPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidosActionPerformed(evt);
            }
        });

        btEnergia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/energia-solar (1).png"))); // NOI18N
        btEnergia.setText("Energia");
        btEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnergiaActionPerformed(evt);
            }
        });

        btComputadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/computador (1).png"))); // NOI18N
        btComputadores.setText("Computadores");
        btComputadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComputadoresActionPerformed(evt);
            }
        });

        btInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/internet.png"))); // NOI18N
        btInternet.setText("Internet");
        btInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInternetActionPerformed(evt);
            }
        });

        btNome.setText("Mudar Nome");
        btNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNomeActionPerformed(evt);
            }
        });

        btSenha.setText("Mudar Senha");
        btSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSenhaActionPerformed(evt);
            }
        });

        jLabel3.setText("Bem Vindo(a) Sr(a).");

        jLabel4.setText(entidade.getNome());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btComputadores, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btNome, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEnergia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btInternet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btComputadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnergiaActionPerformed
        TelaEnergia telaenergia = null;
        try {
            telaenergia = new TelaEnergia(this,entidade);
        } catch (IOException ex) {
            Logger.getLogger(TelaEntidade.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaEntidade.class.getName()).log(Level.SEVERE, null, ex);
        }
        telaenergia.setLocationRelativeTo(null);
        telaenergia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btEnergiaActionPerformed

    private void btPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidosActionPerformed
        TelaPedidos telapedidos = new TelaPedidos(this,entidade);
        telapedidos.setLocationRelativeTo(null);
        telapedidos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btPedidosActionPerformed

    private void btComputadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComputadoresActionPerformed
        TelaComputador telacomputador = null;
        try {
            telacomputador = new TelaComputador(this,entidade);
        } catch (IOException ex) {
            Logger.getLogger(TelaEntidade.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaEntidade.class.getName()).log(Level.SEVERE, null, ex);
        }
        telacomputador.setLocationRelativeTo(null);
        telacomputador.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btComputadoresActionPerformed

    private void btInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInternetActionPerformed
        TelaInternet telainternet = null;
        try {
            telainternet = new TelaInternet(this,entidade);
        } catch (IOException ex) {
            Logger.getLogger(TelaEntidade.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaEntidade.class.getName()).log(Level.SEVERE, null, ex);
        }
        telainternet.setLocationRelativeTo(null);
        telainternet.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btInternetActionPerformed

    private void btNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNomeActionPerformed
        String novoNome =  JOptionPane.showInputDialog("Insira o seu novo nome");
        if (novoNome != null) {
           if (novoNome.isBlank()) {
                JOptionPane.showMessageDialog(null,"O nome inserido não é válido","AVISO" ,JOptionPane.WARNING_MESSAGE);
            }
            else{
                try {
                    entidade.mudarNome(novoNome);
                    jLabel4.setText(entidade.getNome());
                } catch (IOException | ClassNotFoundException e) {
                    JOptionPane.showMessageDialog(null,"Ocorreu um Erro Durante a Mudança de Nome (" + e.toString() + ")" ,"ERRO" ,JOptionPane.ERROR_MESSAGE);
                }

            } 
        }
    }//GEN-LAST:event_btNomeActionPerformed

    private void btSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSenhaActionPerformed
        String novaSenha =  JOptionPane.showInputDialog("Insira o seu novo nome");
        if (novaSenha != null) {
            if (novaSenha.isBlank()) {
                JOptionPane.showMessageDialog(null,"A senha inserida não é válida","AVISO" ,JOptionPane.WARNING_MESSAGE);
            }
            else{
                try {
                    entidade.mudarSenha(novaSenha);
                } catch (IOException | ClassNotFoundException e) {
                    JOptionPane.showMessageDialog(null,"Ocorreu um Erro Durante a Mudança de Senha (" + e.toString() + ")" ,"ERRO" ,JOptionPane.ERROR_MESSAGE);
                }

            }
        }
    }//GEN-LAST:event_btSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btComputadores;
    private javax.swing.JButton btEnergia;
    private javax.swing.JButton btInternet;
    private javax.swing.JButton btNome;
    private javax.swing.JButton btPedidos;
    private javax.swing.JButton btSenha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
