package Telas;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import programa.Computador;
import programa.DiretorDaEscola;
import programa.EntidadeDoGoverno;
import programa.GerenciadorDeArquivos;

/**
 *
 * @author lucas
 */
public class TelaComputador extends javax.swing.JFrame {
    private JFrame paginaAnterior;
    private EntidadeDoGoverno entidade;
    private Computador computador;
    private ArrayList<DiretorDaEscola> listaDiretores;
    private ArrayList<EntidadeDoGoverno> listaEntidade;
    private ArrayList<Computador> listaComputador;
    private String e = "Computador";
    private int indice;
    private int opcao;
    /**
     * Creates new form TelaComputador
     */
    public TelaComputador(JFrame paginaAnterior,EntidadeDoGoverno entidade) throws IOException, ClassNotFoundException {
        this.paginaAnterior= paginaAnterior;
        this.entidade = entidade;
        listaDiretores = carregarDiretores();
        initComponents();
        carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btResolver = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbChamados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chamados Computadores");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/brasil.png")).getImage());

        btResolver.setText("Resolver");
        btResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResolverActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Chamados de computadores");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/computadorgrad.png"))); // NOI18N

        tbChamados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbChamadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbChamados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btResolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btVoltar)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btVoltar)
                            .addComponent(btResolver)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResolverActionPerformed
       if(computador.isResolvido()==false){
             opcao = computador.resolverChamado();
             if(opcao >=10){
                 JOptionPane.showMessageDialog(null,"O chamado de Energia foi criado","Mensagem",JOptionPane.PLAIN_MESSAGE);
                 try {
                     entidade.criaChamadoEnergia(computador.getEscola());
                 } catch (IOException ex) {
                     Logger.getLogger(TelaComputador.class.getName()).log(Level.SEVERE, null, ex);
                 } catch (ClassNotFoundException ex) {
                     Logger.getLogger(TelaComputador.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
             else if(opcao == 11 || opcao == 1){
                 JOptionPane.showMessageDialog(null,"O chamado de Internet foi criado","Mensagem",JOptionPane.PLAIN_MESSAGE);
                 try {
                     entidade.criaChamadoComputador(computador.getEscola());
                 } catch (IOException ex) {
                     Logger.getLogger(TelaComputador.class.getName()).log(Level.SEVERE, null, ex);
                 } catch (ClassNotFoundException ex) {
                     Logger.getLogger(TelaComputador.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
             
            try {
                entidade.mudarNome(entidade.getNome());
            } catch (IOException ex) {
                Logger.getLogger(TelaEnergia.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaEnergia.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Esse chamado já foi resolvido, vá a página de pedidos e faça um novo chamado","Mensagem",JOptionPane.PLAIN_MESSAGE);
        }
        if( computador.isResolvido()==true){
            listaDiretores = carregarDiretores();
            for(int i =0;i<listaDiretores.size();i++){
                DiretorDaEscola diretor = listaDiretores.get(i);
                if( computador.getEscola().getDiretor().getCpf() == diretor.getCpf() &&  computador.getEscola().getDiretor().getNome().equals(diretor.getNome())){
                    for(int j= 0;j<diretor.getPedidos().size();j++){
                        if(e.equals(diretor.getPedidos().get(j).getTipo())){
                            listaDiretores.get(i).getPedidos().get(j).atualizacao(true, " Chamado completo");
                            //JOptionPane.showMessageDialog(null,"pedido atualizado","Menssagem",JOptionPane.PLAIN_MESSAGE);
                        }
                    }
                }
            }
           
            
        }
        else{
            listaDiretores = carregarDiretores();
            for(int i =0;i<listaDiretores.size();i++){
                DiretorDaEscola diretor = listaDiretores.get(i);
                if( computador.getEscola().getDiretor().getCpf() == diretor.getCpf() &&  computador.getEscola().getDiretor().getNome().equals(diretor.getNome())){
                    for(int j= 0;j<diretor.getPedidos().size();j++){
                        if(e.equals(diretor.getPedidos().get(j).getTipo())){
                            listaDiretores.get(i).getPedidos().get(j).atualizacao(true, " Não foi possivel realizar pedido");
                            
                        }
                    }
                }
            }
        }
        atualizarPedidos(listaDiretores);
        try {  
            carregaTabela();
        } catch (IOException ex) {
            Logger.getLogger(TelaComputador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaComputador.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btResolverActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        paginaAnterior.setVisible(true);
        this.setVisible(false);
        this.dispose(); 
    }//GEN-LAST:event_btVoltarActionPerformed

    private void tbChamadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChamadosMouseClicked
        indice = tbChamados.getSelectedRow();
        try {
            listaComputador = carregarComputador();
            computador = listaComputador.get(indice);
        } catch (IOException ex) {
            Logger.getLogger(TelaEnergia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaEnergia.class.getName()).log(Level.SEVERE, null, ex);
        }

        btResolver.setEnabled(true);
    }//GEN-LAST:event_tbChamadosMouseClicked

   public void carregaTabela() throws IOException, ClassNotFoundException{
        listaComputador = carregarComputador();
        //System.out.println(listaComputador.size());
        Object[] colunas = new Object[]{"Diretor","Escola","Numero","Resolvido"};
        Object[][] dadosPedidos = new Object[listaComputador.size()][colunas.length]; 
        for(int i=0;i<listaComputador.size();i++){    
                Object linha[]=new Object[]{listaComputador.get(i).getEscola().getDiretor().getNome(),
                                            listaComputador.get(i).getEscola().getNome(),
                                            listaComputador.get(i).getId(),
                                            listaComputador.get(i).isResolvido()};
                dadosPedidos[i] = linha;  
                   
        }
        DefaultTableModel modelo = new DefaultTableModel(dadosPedidos,colunas);
        tbChamados.setModel(modelo);
        btResolver.setEnabled(false);
    }
   
   
   public ArrayList<Computador> carregarComputador() throws IOException, ClassNotFoundException{
        
        try {
            File arquivo = new File("src\\dados\\usuarios\\chamadosComputador.txt"); 
            GerenciadorDeArquivos<Computador> gerenciadorDeArquivos = new GerenciadorDeArquivos<>();
            if (!arquivo.isDirectory() && arquivo.exists()) {
                listaComputador = gerenciadorDeArquivos.lerArquivo(arquivo);
            }
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null,"Ocorreu um Erro ao abrir os arquivo de Computador (" + e.toString() + ")" ,"ERRO" ,JOptionPane.ERROR_MESSAGE);
        } 
        return this.listaComputador;
    }
    public void atualizarEnergia(ArrayList<Computador> listaComputador){
        this.listaComputador = listaComputador;
        try{
            File arquivo = new File("src\\dados\\usuarios\\chamadosComputador.txt");
            GerenciadorDeArquivos<Computador> gerenciadorDeArquivos = new GerenciadorDeArquivos<>();
            if (!arquivo.isDirectory() && arquivo.exists()) {
                   gerenciadorDeArquivos.EscreverArquivo(listaComputador,arquivo);
                }
        }catch (IOException e) {
                JOptionPane.showMessageDialog(null,"Ocorreu um Erro Durante a escrita do Arquivo de Computador aqui(" + e.toString() + ")" ,"ERRO" ,JOptionPane.ERROR_MESSAGE);
                
        }
    }
    public ArrayList<EntidadeDoGoverno> carregarEntidades() throws IOException, ClassNotFoundException{
        
        try {
            File arquivo = new File("src\\dados\\usuarios\\entidades.txt");
            
            GerenciadorDeArquivos<EntidadeDoGoverno> gerenciadorDeArquivos = new GerenciadorDeArquivos<>();
            listaEntidade = gerenciadorDeArquivos.lerArquivo(arquivo);
            
        } catch (IOException | ClassNotFoundException e) {
            throw e;
        } 
        return this.listaEntidade;
    }
    
    public ArrayList<DiretorDaEscola> carregarDiretores(){
        
        try{
            File arquivoDiretores = new File("src\\dados\\usuarios\\diretores.txt");
            GerenciadorDeArquivos<DiretorDaEscola> gerenciadorDeArquivosDiretores = new GerenciadorDeArquivos<>();
            if (!arquivoDiretores.isDirectory() && arquivoDiretores.exists()) {
                    this.listaDiretores = gerenciadorDeArquivosDiretores.lerArquivo(arquivoDiretores);
                }
        }catch (IOException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null,"Ocorreu um Erro ao abrir os arquivo de Diretores aqui (" + e.toString() + ")" ,"ERRO" ,JOptionPane.ERROR_MESSAGE);
                //this.dispose();
        }
        return this.listaDiretores;
    }
    
    public void atualizarPedidos(ArrayList<DiretorDaEscola> listaDiretores){
        this.listaDiretores = listaDiretores;
        try{
            File arquivoDiretores = new File("src\\dados\\usuarios\\diretores.txt");
            GerenciadorDeArquivos<DiretorDaEscola> gerenciadorDeArquivosDiretores = new GerenciadorDeArquivos<>();
            if (!arquivoDiretores.isDirectory() && arquivoDiretores.exists()) {
                   gerenciadorDeArquivosDiretores.EscreverArquivo(listaDiretores,arquivoDiretores);
                }
        }catch (IOException e) {
                JOptionPane.showMessageDialog(null,"Ocorreu um Erro Durante a escrita do Arquivo de Diretores aqui(" + e.toString() + ")" ,"ERRO" ,JOptionPane.ERROR_MESSAGE);
                //this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btResolver;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbChamados;
    // End of variables declaration//GEN-END:variables
}
