package Telas;

import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import programa.DiretorDaEscola;

/**
 *
 * @author lucas
 */
public class TelaDiretor extends javax.swing.JFrame {
    private JFrame paginaAnterior;
    private DiretorDaEscola diretor;
    /**
     * Creates new form TelaEntidade
     */
    public TelaDiretor(JFrame paginaAnterior, DiretorDaEscola diretor) {
        this.paginaAnterior = paginaAnterior;
        this.diretor = diretor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botaoPedido = new javax.swing.JButton();
        botaoDetalhe = new javax.swing.JButton();
        botaoNome = new javax.swing.JButton();
        botaoSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diretor");

        jLabel1.setText("Bem Vindo(a) Sr(a).");

        jLabel2.setText(diretor.getNome());
        jLabel2.setToolTipText("");

        botaoPedido.setText("Fazer Pedido");
        botaoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPedidoActionPerformed(evt);
            }
        });

        botaoDetalhe.setText("Detalhes dos Pedidos");
        botaoDetalhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDetalheActionPerformed(evt);
            }
        });

        botaoNome.setText("Mudar Nome ");
        botaoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNomeActionPerformed(evt);
            }
        });

        botaoSenha.setText("Mudar Senha");
        botaoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(botaoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoDetalhe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoDetalhe)
                .addGap(18, 18, 18)
                .addComponent(botaoNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoSenha)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPedidoActionPerformed
        TelaPedidoDiretor telaPedidoDiretor = new TelaPedidoDiretor(this, this.diretor);
        telaPedidoDiretor.setLocationRelativeTo(null);
        telaPedidoDiretor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botaoPedidoActionPerformed
    
    private void botaoDetalheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDetalheActionPerformed
        TelaDetalhePedidoDiretor telaDetalhePedidoDiretor = new TelaDetalhePedidoDiretor(this, this.diretor);
        telaDetalhePedidoDiretor.setLocationRelativeTo(null);
        telaDetalhePedidoDiretor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botaoDetalheActionPerformed

    private void botaoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNomeActionPerformed
        String novoNome =  JOptionPane.showInputDialog("Insira o seu novo nome");
        if (novoNome != null) {
           if (novoNome.isBlank()) {
                JOptionPane.showMessageDialog(null,"O nome inserido não é válido","AVISO" ,JOptionPane.WARNING_MESSAGE);
            }
            else{
                try {
                    diretor.mudarNome(novoNome);
                    jLabel2.setText(diretor.getNome());
                } catch (IOException | ClassNotFoundException e) {
                    JOptionPane.showMessageDialog(null,"Ocorreu um Erro Durante a Mudança de Nome (" + e.toString() + ")" ,"ERRO" ,JOptionPane.ERROR_MESSAGE);
                }

            } 
        }    
    }//GEN-LAST:event_botaoNomeActionPerformed

    private void botaoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSenhaActionPerformed
        String novaSenha =  JOptionPane.showInputDialog("Insira o seu novo nome");
        if (novaSenha != null) {
            if (novaSenha.isBlank()) {
                JOptionPane.showMessageDialog(null,"A senha inserida não é válida","AVISO" ,JOptionPane.WARNING_MESSAGE);
            }
            else{
                try {
                    diretor.mudarSenha(novaSenha);
                } catch (IOException | ClassNotFoundException e) {
                    JOptionPane.showMessageDialog(null,"Ocorreu um Erro Durante a Mudança de Senha (" + e.toString() + ")" ,"ERRO" ,JOptionPane.ERROR_MESSAGE);
                }

            }
        }
        
    }//GEN-LAST:event_botaoSenhaActionPerformed

    public void setDiretor(DiretorDaEscola diretor) {
        this.diretor = diretor;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDetalhe;
    private javax.swing.JButton botaoNome;
    private javax.swing.JButton botaoPedido;
    private javax.swing.JButton botaoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
